DANIEL_BANARIBA = "https://www.danielbanariba.com" 

#DIRECCIONES DENTRO DE LA PAGINA
HOME = "/"
MUSICA = "#musica"
MERCADERIA = "#mercaderia"

#REDES SOCIALES
FACEBOOK = "https://www.facebook.com/NihilismoHN"
INSTAGRAM = ""
TWITTER = ""
YOUTUBE = ""
TIKTOK = ""

#PLATAFORMAS DE STREAMING
SPOTIFY = ""
APPLE_MUSIC = ""
YOUTUBE_MUSIC = ""
DEEZER = ""
AMAZON_MUSIC = ""
SOUNDCLOUD = ""
BANDCAMP = ""
TIDAL = ""
NAPSTER = ""


# INTEGRANTE - FACEBOOK
GUITRRISTA_FACEBOOK = ""
VOCALISTA_FACEBOOK = ""
BATERISTA_FACEBOOK = ""
BAJISTA_FACEBOOK = ""

# INTEGRANTE - INSTAGRAM
GUITARRISTA_INSTAGRAM = ""
VOCALISTA_INSTAGRAM = ""
BATERISTA_INSTAGRAM = ""
BAJISTA_INSTAGRAM = ""

# INTEGRANTE - TWITTER
GUITARRISTA_TWITTER = ""
VOCALISTA_TWITTER = ""
BATERISTA_TWITTER = ""
BAJISTA_TWITTER = ""

# INTEGRANTE - YOUTUBE
GUITARRISTA_YOUTUBE = ""
VOCALISTA_YOUTUBE = ""
BATERISTA_YOUTUBE = ""
BAJISTA_YOUTUBE = ""

# INTEGRANTE - TIKTOK
GUITARRISTA_TIKTOK = ""
VOCALISTA_TIKTOK = ""   
BATERISTA_TIKTOK = ""
BAJISTA_TIKTOK = ""

#VENDEDOR - WHATSAPP#TODO Examinar lo que GPT me genero, creo que es una forma para generar mensajes personalizados
WHATSAPP = "https://api.whatsapp.com/send?phone=5491130777777&text=Hola!%20Quiero%20comprar%20una%20remera%20de%20Nihilismo%20Web"